import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-slate-100 bg-[radial-gradient(ellipse_at_top,rgb(99_102_241_/_12%),transparent_65%)] px-4 py-12 font-[family-name:var(--font-geist-sans)] text-slate-900 sm:px-6 dark:bg-slate-950 dark:text-slate-200">{children}</body>
    </html>
  );
}
